package com.github.charlieboggus.turborecs.db.repository

import com.github.charlieboggus.turborecs.db.entities.MediaTagEntity
import org.springframework.data.jpa.repository.JpaRepository
import java.util.UUID

interface MediaTagRepository : JpaRepository<MediaTagEntity, UUID> {

    // Get all tags for a media item (for displaying on the metadata view)
    fun findAllByMediaItemId(mediaItemId: UUID): List<MediaTagEntity>

    // Wipe tags for a media item before re-tagging (e.g. model version upgrade)
    fun deleteAllByMediaItemId(mediaItemId: UUID)

    // Get all tags generated by a specific model version (for the recommendation engine)
    fun findAllByModelVersion(modelVersion: String): List<MediaTagEntity>
}